### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Not Found").

### ISSUE THREAD

**Issue by titamrtn** [Harborn-digital/cookie-consent-bundle#109]
Hi,

I've just installed this bundle, everything was created by flex. I've just add esi in framework
 I'm using symfony 5.4

I changed my packages/ch_cookie_consent.yaml to this

```yaml
ch_cookie_consent:
    theme: 'light'
    categories:
        - 'analytics'
        - 'tracking'
        - 'marketing'
        - 'social_media'
    position: 'bottom' # top, bottom
    simplified: true
```
When i try to render the page i got `An exception has been thrown during the rendering of a template ("Not Found").`

![image](https://user-images.githubusercontent.com/5078563/155702485-bca2e93a-16db-406f-a594-4c6aad67f564.png)
