### ISSUE TITLE
Simplified version still shows categories

### ISSUE THREAD

**Issue by NiklasBr** [Harborn-digital/cookie-consent-bundle#61]
Categories are still rendered when using the simplified option:

![Screenshot (12)](https://user-images.githubusercontent.com/279826/80594591-95352d00-8a23-11ea-9859-498114889ef0.png)

I tried to check out the commit ff7d578bc664406701cdb2d64b34fb9fef84a35f
 and configure with `simplified: true`, however, when I did so the result was that both the complex categories and the simplified version appeared next to each other:

```yml
ch_cookie_consent:
    position: 'top'
    simplified: true
    theme: 'dark'
    use_logger: false
```

But this then shows both the simplified buttons: "Only use functional cookies"/"Allow all cookies" *and* "Do you want tracking cookies? Yes/No" + "Do you want personalised ads? Yes/No" + "Do you want social media cookies? Yes/No"

This isn't the intention, right?
